### ISSUE TITLE
Type error on current HEAD

### ISSUE THREAD

**Issue by vmx** [ipfs/js-ipfs#3527]
- **Version**: 9cbc09c03ebe66a64f18f5781a801d37d9450a02
- **Platform**: Linux gene 5.9.0-4-amd64 #1 SMP Debian 5.9.11-1 (2020-11-27) x86_64 GNU/Linu
- **Subsystem**: core

#### Description:

`npm install` errors. From the output I can't tell if it's a fatal error (and the installation actually works) or if it's an error that can be ignored.

I checked the source out and ran `npm install`. It failed with

```console
> ipfs-core@0.5.1 prepare /tmp/js-ipfs/packages/ipfs-core
> aegir build --no-bundle

src/components/block/put.js:85:46 - error TS2345: Argument of type 'Uint8Array | Block' is not assignable to parameter of type 'Uint8Array'.
  Type 'Block' is missing the following properties from type 'Uint8Array': BYTES_PER_ELEMENT, buffer, byteLength, byteOffset, and 26 more.

85         const multihash = await multihashing(block, mhtype)
                                                ~~~~~


Found 1 error.

Command failed with exit code 2: tsc --build /tmp/js-ipfs/packages/ipfs-core/tsconfig-types.aegir.json
lerna info lifecycle ipfs-core@0.5.1~prepare: Failed to exec prepare script
```

When I run `$ npx aegir build --no-bundle` directly in `packages/ipfs-core`, I get the same error. `tsc` is at version `4.1.3`.

I expected that an `npm install` is successful.

#### Steps to reproduce the error:

```console
$ git clone https://github.com/ipfs/js-ipfs 
$ cd js-ipfs
$ npm install
```

**Comment by achingbrain** [comment]
Looks like the types introduced by https://github.com/multiformats/js-multihashing-async/pull/92 went out as a minor which has broken things.
