### ISSUE TITLE
App crashes on runtime bundling with webpack: `Error: Cannot find module './fetch.node'`

### ISSUE THREAD

**Issue by pablomendezroyo** [ipfs/js-ipfs#4285]
- **Version**:

Ipfs dependencies on my project
```
    "ipfs-car": "^0.9.1",
    "ipfs-http-client": "^59.0.0",
```
- **Platform**:

Node JS app running on Docker container
- **Subsystem**:

Looks like the affected sub-dependency is `ipfs-utils` used by `ipfs-core-utils` used by `ipfs-http-client`
See dependency subgraph
```
yarn why ipfs-utils
[1/4] Why do we have the module "ipfs-utils"...?
...
=> Found "ipfs-utils@9.0.9"
info Reasons this module exists
   - "_project_#@dappnode#dappmanager#ipfs-car" depends on it
   - Hoisted from "_project_#@dappnode#dappmanager#ipfs-car#ipfs-utils"
   - Hoisted from "_project_#@dappnode#dappmanager#ipfs-http-client#ipfs-utils"
   - Hoisted from "_project_#@dappnode#dappmanager#ipfs-car#ipfs-core-utils#ipfs-utils"
   - Hoisted from "_project_#@dappnode#dappmanager#ipfs-http-client#ipfs-core-utils#ipfs-utils"
```

#### Severity:

Critical. NodeJS app crashes at runtime. App built with webpack

#### Description:

- NodeJS app built with webpack
- App crashes with the following error
```
/usr/src/app/webpack:/node_modules/ipfs-utils/src/http/ sync:2
        var e = new Error("Cannot find module '" + req + "'");
^
Error: Cannot find module './fetch.node'
    at webpackEmptyContext (/usr/src/app/webpack:/node_modules/ipfs-utils/src/http/ sync:2:1)
    at Object.4910 (/usr/src/app/webpack:/node_modules/ipfs-utils/src/http/fetch.js:20:15)
    at __webpack_require__ (/usr/src/app/webpack:/@dappnode/dappmanager/webpack/bootstrap:19:1)
    at Object.29397 (/usr/src/app/webpack:/node_modules/ipfs-utils/src/http.js:4:37)
    at __webpack_require__ (/usr/src/app/webpack:/@dappnode/dappmanager/webpack/bootstrap:19:1)
    at Object.253 (/usr/src/app/index.js:390790:12)
    at __webpack_require__ (/usr/src/app/webpack:/@dappnode/dappmanager/webpack/bootstrap:19:1)
    at /usr/src/app/webpack:/@dappnode/dappmanager/webpack/startup:4:1
    at Object.<anonymous> (/usr/src/app/index.js:450350:12)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47
 ```
Looks like the `fetch.node.js` from ipfs-utils cannot be found. See https://github.com/ipfs/js-ipfs-utils/blob/5faabb4b128d32fa095d64a1cdf04c4992cd4f15/src/http/fetch.js#L11

- Application should not crash

#### Steps to reproduce the error:

Create node app and build with webpack (`  "webpack": "^5.52.0",`) and the following `webpack.config.js`
```
import path from "path";
import webpack from "webpack";
import { fileURLToPath } from "url";
const { NODE_ENV = "production" } = process.env;

const __dirname = path.dirname(fileURLToPath(import.meta.url));

export default {
  entry: "./src/index.ts",
  mode: NODE_ENV,
  target: "node",
  output: {
    path: path.resolve(__dirname, "build"),
    filename: "index.js"
  },
  // externals: [/node_modules/, "bufferutil", "utf-8-validate"],
  resolve: {
    extensions: [".ts", ".js"],
    fallback: {
      electron: false
    }
  },
  module: {
    rules: [
      {
        test: /\.m?js/,
        resolve: {
          fullySpecified: false
        }
      },
      {
        test: /\.ts$/,
        use: ["ts-loader"]
      },
      {
        test: /\.node$/,
        loader: "node-loader"
      }
    ]
  },
  plugins: [
    new webpack.ProvidePlugin({
      WebSocket: "ws",
      fetch: ["node-fetch", "default"]
    })
  ],
  optimization: {
    // Minimization does not provide great disk space savings, but reduces debug capacity
    minimize: false
  },
  devtool: "source-map"
};
```

**Comment by pablomendezroyo** [comment]
I managed to make it work by patching the library `ipfs-utils`. Not sure what the issue but my guess is that setting the lib to be exported in a `let` var is not good. I've modified the files:
- `node_modules/ipfs-utils/src/fetch.js b/node_modules/ipfs-utils/src/fetch.js` 
- `node_modules/ipfs-utils/src/http/fetch.js b/node_modules/ipfs-utils/src/http/fetch.js` 

For anyone interested, checkout this commit https://github.com/dappnode/DNP_DAPPMANAGER/pull/1341/commits/37ac71b14d17ff4eb143da2760498a91e6d37435

**Comment by hubingliang** [comment]
i got same issue when i use next13 build app
hope fix asap

**Comment by rocky-fleek** [comment]
Same issue here with next 13.2.3 :/

**Comment by alex-nax** [comment]
Same issue, next 13.2.4

**Comment by apostgit** [comment]
Issue still exists. Can someone give a solution or work around as this doesn't let us complete a functions.

**Comment by achingbrain** [comment]
js-IPFS is in the process of being deprecated, the replacement is [Helia](https://github.com/ipfs/helia) - please see the [State of IPFS in JS](https://blog.ipfs.tech/state-of-ipfs-in-js/) post for a bit of background and the [migration guide](https://github.com/ipfs/helia/wiki/Migrating-from-js-IPFS) for how to port your app over.

You're using `ipfs-http-client` - if you are talking to a Kubo node, please use [kubo-rpc-client](https://github.com/ipfs/js-kubo-rpc-client) instead and open any issues there.

There are examples for using Helia with popular bundlers and frameworks, they have working config you can copy/paste so hopefully these are helpful:

* https://github.com/ipfs-examples/helia-nextjs
* https://github.com/ipfs-examples/helia-webpack

If not, please open an issue on the [examples repo](https://github.com/ipfs-examples/helia-examples) for examples you'd like to see.
