### ISSUE TITLE
npm fail

### ISSUE THREAD

**Issue by xuruijing** [ipfs/js-ipfs#1341]
I run this command in Mac
> sudo npm install ipfs --global

result a warnning "deprecated libp2p-multiplex@0.5.1: use libp2p-mplex instead"

and a error "Command failed: /usr/bin/git clone -q git://github.com/dignifiedquire/multiplex.git /Users/xuruijing/.npm/_cacache/tmp/git-clone-c8dde9da
npm ERR! /Users/xuruijing/.npm/_cacache/tmp/git-clone-c8dde9da/.git: Permission denied"

why?   Who has run into such a problem?

npm -v
5.6.0

node -v
v8.11.1

**Comment by xuruijing** [comment]
According to the NPM documentation you provided, I installed the NVM and used the command "npm install ipfs --global", There are other errors in execution results.

node-pre-gyp ERR! Tried to download(403): https://node-binaries.s3.amazonaws.com/gcstats/v1.1.1/Release/node-v64-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for gc-stats@1.1.1 and node@10.0.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp)



In file included from ../node_modules/nan/nan.h:192:
../node_modules/nan/nan_maybe_43_inl.h:112:15: error: no member named 'ForceSet'
      in 'v8::Object'
  return obj->ForceSet(isolate->GetCurrentContext(), key, value, attribs);
         ~~~  ^

npm -v
5.6.0

node -v
v10.0.0

**Comment by alanshaw** [comment]
@xuruijing I'll look into this, I might have come across the same problem

**Comment by VictorBjelkholm** [comment]
Yeah, I'm pretty sure js-ipfs doesn't currently work with 10.0.0. Some packages even define that they don't work with 10.0.0 and if you're using yarn, it won't even try to install the dependencies because of the strictness.

**Comment by xuruijing** [comment]
I changed node.js to version 8.11.1, and the compilation will not show the last error, but the previous error still exists, and I wonder if it will affect the running of ipfs？

**Comment by alanshaw** [comment]
Looks like `js-ipfs-repo` depends on level.js (a fork) and leveldown as well as datastore-level. It shims out `leveldown` for `level.js` in the browser.

I think @richardschneider is [right](https://github.com/ipfs/js-ipfs-repo/issues/127#issuecomment-341926469) this should be pushed into `datastore-level`.

It would be great to sort that out as well whilst upgrading leveldown to a version that works with Node.js 10.x.

**Comment by xuruijing** [comment]
Also, do I have to install it manually?

npm WARN dirty-chai@2.0.1 requires a peer of chai@>=2.2.1 <5 but none is installed. You must install peer dependencies yourself.

**Comment by alanshaw** [comment]
> I changed node.js to version 8.11.1, and the compilation will not show the last error, but the previous error still exists, and I wonder if it will affect the running of ipfs？

Which error are you referring to?

**Comment by xuruijing** [comment]
node-pre-gyp ERR! Tried to download(403): https://node-binaries.s3.amazonaws.com/gcstats/v1.1.1/Release/node-v57-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for gc-stats@1.1.1 and node@8.11.1 (node-v57 ABI, unknown) (falling back to source compile with node-gyp) 


This error still exists after changing the node.js version.

**Comment by alanshaw** [comment]
@xuruijing I think that's ok, it just means that npm has had to compile something because a pre-built binary didn't exist.

**Comment by alanshaw** [comment]
I've created an issue here to track the Node.js 10.x issue: https://github.com/ipfs/js-ipfs/issues/1347

Thanks @xuruijing
